{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tee-sniper.fullname" . }}
  labels:
    {{- include "tee-sniper.labels" . | nindent 4 }}
type: Opaque
stringData:
  TS_USERNAME: {{ .Values.secrets.username | quote }}
  TS_PIN: {{ .Values.secrets.pin | quote }}
  TS_FROM_NUMBER: {{ .Values.secrets.fromNumber | quote }}
  TS_TO_NUMBER: {{ .Values.secrets.toNumber | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.twilioAccountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilioAuthToken | quote }}
{{- end }}
